"""Constants for Matrix Lamp component for ESPHome."""

MAXICONS = 100
MAXFRAMES = 110

ICONWIDTH = 8
ICONHEIGHT = 8

IS_8X8 = 64

DEF_TYPE = "RGB565"

CONF_BITMAP = "bitmap"
CONF_SCALE_ID = "scale_id"
CONF_SPEED_ID = "speed_id"
CONF_ORIENTATION = "matrix_orientation"
CONF_MATRIX_TYPE = "matrix_type"
CONF_MATRIX_ID = "matrix_lamp_id"
CONF_ICONS = "icons"
CONF_INTENSITY_ID = "intensity_id"
CONF_CACHE = "iconscache"
CONF_LAMEID = "lameid"
CONF_RGB565ARRAY = "str565"
CONF_FRAMEDURATION = "frame_duration"
CONF_FRAMEINTERVAL = "frame_interval"
CONF_PINGPONG = "pingpong"

CONF_ON_EFFECT_START = "on_effect_start"

EFF_WHITE_COLOR = "WHITE_COLOR"
EFF_COLORS = "COLORS"
EFF_MADNESS = "MADNESS"
EFF_CLOUDS = "CLOUDS"
EFF_LAVA = "LAVA"
EFF_PLASMA = "PLASMA"
EFF_RAINBOW = "RAINBOW"
EFF_RAINBOW_STRIPE = "RAINBOW_STRIPE"
EFF_ZEBRA = "ZEBRA"
EFF_FOREST = "FOREST"
EFF_OCEAN = "OCEAN"
EFF_BBALLS = "BBALLS"
EFF_BALLS_BOUNCE = "BALLS_BOUNCE"
EFF_POPCORN = "POPCORN"
EFF_SPIRO = "SPIRO"
EFF_PRISMATA = "PRISMATA"
EFF_SMOKEBALLS = "SMOKEBALLS"
EFF_FLAME = "FLAME"
EFF_FIRE_2021 = "FIRE_2021"
EFF_PACIFIC = "PACIFIC"
EFF_SHADOWS = "SHADOWS"
EFF_DNA = "DNA"
EFF_FLOCK = "FLOCK"
EFF_FLOCK_N_PR = "FLOCK_N_PR"
EFF_BUTTERFLYS = "BUTTERFLYS"
EFF_BUTTERFLYS_LAMP = "BUTTERFLYS_LAMP"
EFF_SNAKES = "SNAKES"
EFF_NEXUS = "NEXUS"
EFF_SPHERES = "SPHERES"
EFF_SINUSOID3 = "SINUSOID3"
EFF_METABALLS = "METABALLS"
EFF_AURORA = "AURORA"
EFF_SPIDER = "SPIDER"
EFF_LAVALAMP = "LAVALAMP"
EFF_LIQUIDLAMP = "LIQUIDLAMP"
EFF_LIQUIDLAMP_AUTO = "LIQUIDLAMP_AUTO"
EFF_DROPS = "DROPS"
EFF_MATRIX = "MATRIX"
EFF_FIRE_2012 = "FIRE_2012"
EFF_FIRE_2018 = "FIRE_2018"
EFF_FIRE_2020 = "FIRE_2020"
EFF_FIRE = "FIRE"
EFF_WHIRL = "WHIRL"
EFF_WHIRL_MULTI = "WHIRL_MULTI"
EFF_MAGMA = "MAGMA"
EFF_LLAND = "LLAND"
EFF_WATERFALL = "WATERFALL"
EFF_WATERFALL_4IN1 = "WATERFALL_4IN1"
EFF_POOL = "POOL"
EFF_PULSE = "PULSE"
EFF_PULSE_RAINBOW = "PULSE_RAINBOW"
EFF_PULSE_WHITE = "PULSE_WHITE"
EFF_OSCILLATING = "OSCILLATING"
EFF_FOUNTAIN = "FOUNTAIN"
EFF_FAIRY = "FAIRY"
EFF_COMET = "COMET"
EFF_COMET_COLOR = "COMET_COLOR"
EFF_COMET_TWO = "COMET_TWO"
EFF_COMET_THREE = "COMET_THREE"
EFF_ATTRACT = "ATTRACT"
EFF_FIREFLY = "FIREFLY"
EFF_FIREFLY_TOP = "FIREFLY_TOP"
EFF_SNAKE = "SNAKE"
EFF_SPARKLES = "SPARKLES"
EFF_TWINKLES = "TWINKLES"
EFF_SMOKE = "SMOKE"
EFF_SMOKE_COLOR = "SMOKE_COLOR"
EFF_PICASSO = "PICASSO"
EFF_WAVES = "WAVES"
EFF_SAND = "SAND"
EFF_RINGS = "RINGS"
EFF_CUBE2D = "CUBE2D"
EFF_SIMPLE_RAIN = "SIMPLE_RAIN"
EFF_STORMY_RAIN = "STORMY_RAIN"
EFF_COLOR_RAIN = "COLOR_RAIN"
EFF_SNOW = "SNOW"
EFF_STARFALL = "STARFALL"
EFF_LEAPERS = "LEAPERS"
EFF_LIGHTERS = "LIGHTERS"
EFF_LIGHTER_TRACES = "LIGHTER_TRACES"
EFF_LUMENJER = "LUMENJER"
EFF_PAINTBALL = "PAINTBALL"
EFF_RAINBOW_VER = "RAINBOW_VER"
EFF_CHRISTMAS_TREE = "CHRISTMAS_TREE"
EFF_BY_EFFECT = "BY_EFFECT"
EFF_COLOR_FRIZZLES = "COLOR_FRIZZLES"
EFF_COLORED_PYTHON = "COLORED_PYTHON"
EFF_CONTACTS = "CONTACTS"
EFF_DROP_IN_WATER = "DROP_IN_WATER"
EFF_FEATHER_CANDLE = "FEATHER_CANDLE"
EFF_FIREWORK = "FIREWORK"
EFF_FIREWORK_2 = "FIREWORK_2"
EFF_HOURGLASS = "HOURGLASS"
EFF_FLOWERRUTA = "FLOWERRUTA"
EFF_MAGIC_LANTERN = "MAGIC_LANTERN"
EFF_MOSAIC = "MOSAIC"
EFF_OCTOPUS = "OCTOPUS"
EFF_PAINTS = "PAINTS"
EFF_PLASMA_WAVES = "PLASMA_WAVES"
EFF_RADIAL_WAVE = "RADIAL_WAVE"
EFF_RIVERS = "RIVERS"
EFF_SPECTRUM = "SPECTRUM"
EFF_STROBE = "STROBE"
EFF_SWIRL = "SWIRL"
EFF_TORNADO = "TORNADO"
EFF_WATERCOLOR = "WATERCOLOR"
EFF_WEB_TOOLS = "WEB_TOOLS"
EFF_WINE = "WINE"
EFF_BAMBOO = "BAMBOO"
EFF_BALLROUTINE = "BALLROUTINE"
EFF_STARS = "STARS"
EFF_TIXYLAND = "TIXYLAND"
EFF_FIRESPARKS = "FIRESPARKS"
EFF_DANDELIONS = "DANDELIONS"
EFF_SERPENTINE = "SERPENTINE"
EFF_TURBULENCE = "TURBULENCE"
EFF_ARROWS = "ARROWS"
EFF_AVRORA = "AVRORA"
EFF_LOTUS = "LOTUS"
EFF_FONTAN = "FONTAN"
EFF_NIGHTCITY = "NIGHTCITY"
EFF_RAIN = "RAIN"
EFF_SCANNER = "SCANNER"
EFF_MIRAGE = "MIRAGE"
EFF_HANDFAN = "HANDFAN"
EFF_LIGHTFILTER = "LIGHTFILTER"
EFF_TASTEHONEY = "TASTEHONEY"
EFF_SPINDLE = "SPINDLE"
EFF_POPURI = "POPURI"
EFF_RAINBOW_SPOT = "RAINBOW_SPOT"
EFF_RAINBOW_RINGS = "RAINBOW_RINGS"
EFF_VYSHYVANKA = "VYSHYVANKA"
EFF_INCREMENTALDRIFT = "INCREMENTAL_DRIFT"
EFF_UKRAINE = "UKRAINE"

MATRIX_LAMP_EFFECTS = [
    EFF_WHITE_COLOR,
    EFF_COLORS,
    EFF_MADNESS,
    EFF_CLOUDS,
    EFF_LAVA,
    EFF_PLASMA,
    EFF_RAINBOW,
    EFF_RAINBOW_STRIPE,
    EFF_ZEBRA,
    EFF_FOREST,
    EFF_OCEAN,
    EFF_BBALLS,
    EFF_BALLS_BOUNCE,
    EFF_POPCORN,
    EFF_SPIRO,
    EFF_PRISMATA,
    EFF_SMOKEBALLS,
    EFF_FLAME,
    EFF_FIRE_2021,
    EFF_PACIFIC,
    EFF_SHADOWS,
    EFF_DNA,
    EFF_FLOCK,
    EFF_FLOCK_N_PR,
    EFF_BUTTERFLYS,
    EFF_BUTTERFLYS_LAMP,
    EFF_SNAKES,
    EFF_NEXUS,
    EFF_SPHERES,
    EFF_SINUSOID3,
    EFF_METABALLS,
    EFF_AURORA,
    EFF_SPIDER,
    EFF_LAVALAMP,
    EFF_LIQUIDLAMP,
    EFF_LIQUIDLAMP_AUTO,
    EFF_DROPS,
    EFF_MATRIX,
    EFF_FIRE_2012,
    EFF_FIRE_2018,
    EFF_FIRE_2020,
    EFF_FIRE,
    EFF_WHIRL,
    EFF_WHIRL_MULTI,
    EFF_MAGMA,
    EFF_LLAND,
    EFF_WATERFALL,
    EFF_WATERFALL_4IN1,
    EFF_POOL,
    EFF_PULSE,
    EFF_PULSE_RAINBOW,
    EFF_PULSE_WHITE,
    EFF_OSCILLATING,
    EFF_FOUNTAIN,
    EFF_FAIRY,
    EFF_COMET,
    EFF_COMET_COLOR,
    EFF_COMET_TWO,
    EFF_COMET_THREE,
    EFF_ATTRACT,
    EFF_FIREFLY,
    EFF_FIREFLY_TOP,
    EFF_SNAKE,
    EFF_SPARKLES,
    EFF_TWINKLES,
    EFF_SMOKE,
    EFF_SMOKE_COLOR,
    EFF_PICASSO,
    EFF_WAVES,
    EFF_SAND,
    EFF_RINGS,
    EFF_CUBE2D,
    EFF_SIMPLE_RAIN,
    EFF_STORMY_RAIN,
    EFF_COLOR_RAIN,
    EFF_SNOW,
    EFF_STARFALL,
    EFF_LEAPERS,
    EFF_LIGHTERS,
    EFF_LIGHTER_TRACES,
    EFF_LUMENJER,
    EFF_PAINTBALL,
    EFF_RAINBOW_VER,
    EFF_CHRISTMAS_TREE,
    EFF_BY_EFFECT,
    EFF_COLOR_FRIZZLES,
    EFF_COLORED_PYTHON,
    EFF_CONTACTS,
    EFF_DROP_IN_WATER,
    EFF_FEATHER_CANDLE,
    EFF_FIREWORK,
    EFF_FIREWORK_2,
    EFF_HOURGLASS,
    EFF_FLOWERRUTA,
    EFF_MAGIC_LANTERN,
    EFF_MOSAIC,
    EFF_OCTOPUS,
    EFF_PAINTS,
    EFF_PLASMA_WAVES,
    EFF_RADIAL_WAVE,
    EFF_RIVERS,
    EFF_SPECTRUM,
    EFF_STROBE,
    EFF_SWIRL,
    EFF_TORNADO,
    EFF_WATERCOLOR,
    EFF_WEB_TOOLS,
    EFF_WINE,
    EFF_BAMBOO,
    EFF_BALLROUTINE,
    EFF_STARS,
    EFF_TIXYLAND,
    EFF_FIRESPARKS,
    EFF_DANDELIONS,
    EFF_SERPENTINE,
    EFF_TURBULENCE,
    EFF_ARROWS,
    EFF_AVRORA,
    EFF_LOTUS,
    EFF_FONTAN,
    EFF_NIGHTCITY,
    EFF_RAIN,
    EFF_SCANNER,
    EFF_MIRAGE,
    EFF_HANDFAN,
    EFF_LIGHTFILTER,
    EFF_TASTEHONEY,
    EFF_SPINDLE,
    EFF_POPURI,
    EFF_RAINBOW_SPOT,
    EFF_RAINBOW_RINGS,
    EFF_VYSHYVANKA,
    EFF_INCREMENTALDRIFT,
    EFF_UKRAINE,
]
