# Common sensors for ESP8266

binary_sensor:
  # ESP Status
  - !include ../common/binary_sensor/status.yaml

text_sensor:
  # ESPHome Version
  - !include ../common/text_sensor/version.yaml

  # Uptime
  - !include ../common/text_sensor/uptime.yaml

sensor:
  # Uptime
  - !include ../common/sensor/uptime.yaml

  # WiFi Signal
  - !include ../common/sensor/wifi-signal.yaml

button:
  # Restart
  - !include ../common/button/restart.yaml