### debug
debug:
  update_interval: 30s
text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
sensor:
  - platform: debug
    free:
      name: "Heap Free"
#    fragmentation: #  Only available on ESP8266 with Arduino 2.5.2+
#      name: "Heap Fragmentation"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    cpu_frequency:
      name: "CPU Frequency"