# Common for ld2410 disable default
ld2420:

uart:
  id: ld2420_uart
  tx_pin: ${tx_pin}
  rx_pin: ${rx_pin}
  baud_rate: 115200
  parity: NONE
  data_bits: 8
  stop_bits: 1

binary_sensor:
  - !include ../common/binary_sensor/ld2420.yaml
#  - platform: ld2420
#    has_target:
#      name: Presence
#      id: presence
text_sensor:
  - !include ../common/text_sensor/ld2420_disable.yaml
#  - platform: ld2420
#    fw_version:
#      name: LD2420 Firmware
#      disabled_by_default: true
sensor:
  - !include ../common/sensor/ld2420.yaml
#  - platform: ld2420
#    moving_distance:
#      name : Moving Distance
#      id: moving_distance
select:
  - !include ../common/select/ld2420_disable.yaml
#  - platform: ld2420
#    operating_mode:
#      name: Operating Mode
#      disabled_by_default: true
number:
  - !include ../common/number/ld2420_disable.yaml
#  - platform: ld2420
#    presence_timeout:
#      name: Detection Presence Timeout
#    min_gate_distance:
#      name: Detection Gate Minimum
#      disabled_by_default: true
#    max_gate_distance:
#      name: Detection Gate Maximum
#      disabled_by_default: true

#    gate_move_sensitivity:
#      name: Move Calibration Sensitivity Factor
#      disabled_by_default: true
#    gate_still_sensitivity:
#      name: Still Calibration Sensitivity Factor
#      disabled_by_default: true
#    gate_0:
#      move_threshold:
#        name: Gate 0 Move Threshold
#        disabled_by_default: true
#      still_threshold:
#        name: Gate 0 Still Threshold
#        disabled_by_default: true
#    gate_1:
#      move_threshold:
#        name: Gate 1 Move Threshold
#        disabled_by_default: true
#      still_threshold:
#        name: Gate 1 Still Threshold
#        disabled_by_default: true
button:
  - !include ../common/button/ld2420_disable.yaml
#  - platform: ld2420
#    apply_config:
#      name: Apply Config
#      disabled_by_default: true
#    factory_reset:
#      name: Factory Reset
#      disabled_by_default: true
#    restart_module:
#      name: Restart Module
#      disabled_by_default: true
#    revert_config:
#      name: Undo Edits
#      disabled_by_default: true